### ISSUE TITLE
networkerror, fixed with a restart

### ISSUE THREAD

**Issue by ericmigi** [mautrix/googlechat#15]
can the bridge detect these kinds of things and automatically reboot itself? It was fixed by a docker restart

```
[2020-02-25 08:14:03,486] [INFO@hangups.client] Received new client_id: 'lcsw_hangouts_1D822926'
[2020-02-25 08:14:03,487] [INFO@hangups.client] Adding channel services...
[2020-02-25 08:14:03,894] [INFO@hangups.client] Channel services added
[2020-02-25 08:14:59,713] [INFO@hangups.channel] Opening new long-polling request
[2020-02-25 08:18:35,414] [INFO@hangups.channel] Opening new long-polling request
[2020-02-25 08:22:40,654] [INFO@hangups.channel] Opening new long-polling request
[2020-02-25 08:24:08,389] [WARNING@hangups.channel] Long-polling interrupted: SID is about to expire
[2020-02-25 08:24:08,391] [INFO@hangups.channel] retry attempt count is now 1
[2020-02-25 08:24:08,392] [INFO@hangups.channel] Backing off for 2 seconds
[2020-02-25 08:24:10,395] [INFO@hangups.channel] Requesting new gsessionid and SID...
[2020-02-25 08:24:10,625] [INFO@hangups.http_utils] Request returned unexpected status: 404 Not Found
[2020-02-25 08:24:10,626] [ERROR@mau.user.@eric:eric.nova.chat] Exception in connection
Traceback (most recent call last):
  File "/opt/mautrix-hangouts/mautrix_hangouts/user.py", line 163, in start
    await self.client.connect()
  File "/usr/lib/python3.7/site-packages/hangups/client.py", line 138, in connect
    await self._listen_future
  File "/usr/lib/python3.7/site-packages/hangups/channel.py", line 188, in listen
    await self._fetch_channel_sid()
  File "/usr/lib/python3.7/site-packages/hangups/channel.py", line 257, in _fetch_channel_sid
    res = await self.send_maps([])
  File "/usr/lib/python3.7/site-packages/hangups/channel.py", line 233, in send_maps
    'post', CHANNEL_URL, params=params, data=data_dict
  File "/usr/lib/python3.7/site-packages/hangups/http_utils.py", line 88, in fetch
    .format(res.status, res.reason)
hangups.exceptions.NetworkError: Request return unexpected status: 404: Not Found
```

**Comment by matrixes** [comment]
I saw the exact same exception in my logs. I'm using a dockerised instance of this, and a restart of the container made it come back online again.
It makes me wonder if, for the time being, it would be possible to catch this specific exception and restart the python script?
