### ISSUE TITLE
Probleme start googlechat 

### ISSUE THREAD

**Issue by barto95100** [mautrix/googlechat#79]
Hi thank's for your work

I install and configure de bridge googlechat

but when I start 

python -m mautrix_googlechat --ignore-foreign-tables

````
[2022-10-10 18:59:04,426] [INFO@mau.init] Initializing mautrix-googlechat 0.3.3
[2022-10-10 18:59:04,428] [INFO@mau.init] Initialization complete in 0.1 seconds
[2022-10-10 18:59:04,429] [DEBUG@mau.init] Running startup actions...
[2022-10-10 18:59:04,429] [DEBUG@mau.init] Starting database...
[2022-10-10 18:59:04,429] [DEBUG@mau.db] Connecting to postgres://synapse_user:password-redacted@localhost/synapse
[2022-10-10 18:59:04,467] [DEBUG@mau.db.upgrade] Database at v4, not upgrading
[2022-10-10 18:59:04,469] [DEBUG@mau.client.db.upgrade] Database at v2, not upgrading
[2022-10-10 18:59:04,469] [DEBUG@mau.init] Starting appservice...
[2022-10-10 18:59:04,469] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:29320
[2022-10-10 18:59:04,470] [INFO@mau.mx] Ensuring connectivity to homeserver
[2022-10-10 18:59:04,482] [DEBUG@mau.mx] **Whoami endpoint returned M_FORBIDDEN, trying to register bridge bot before retrying...**
[2022-10-10 18:59:04,487] [CRITICAL@mau.init] Unexpected error in main event loop
Traceback (most recent call last):
  File "/root/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 173, in wait_for_connection
    await self.az.intent.whoami()
  File "/root/lib/python3.9/site-packages/mautrix/client/api/authentication.py", line 174, in whoami
    resp = await self.api.request(Method.GET, Path.v3.account.whoami)
  File "/root/lib/python3.9/site-packages/mautrix/api.py", line 376, in request
    return await self._send(method, full_url, req_content, query_params, headers or {})
  File "/root/lib/python3.9/site-packages/mautrix/api.py", line 255, in _send
    raise make_request_error(
mautrix.errors.request.MForbidden: **Application service has not registered this user (@googlechatbot:snf.fr)**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 613, in ensure_registered
    await self._register()
  File "/root/lib/python3.9/site-packages/mautrix/api.py", line 376, in request
    return await self._send(method, full_url, req_content, query_params, headers or {})
  File "/root/lib/python3.9/site-packages/mautrix/api.py", line 255, in _send
    raise make_request_error(
mautrix.errors.request.MExclusive: **Invalid user localpart for this application service.**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/lib/python3.9/site-packages/mautrix/util/program.py", line 221, in _run
    self.loop.run_until_complete(self.start())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/lib/python3.9/site-packages/mautrix_googlechat/__main__.py", line 83, in start
    await super().start()
  File "/root/lib/python3.9/site-packages/mautrix/bridge/bridge.py", line 211, in start
    await self.matrix.wait_for_connection()
  File "/root/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 184, in wait_for_connection
    await self.az.intent.ensure_registered()
  File "/root/lib/python3.9/site-packages/mautrix/appservice/api/intent.py", line 617, in ensure_registered
    raise IntentError(f"Failed to register {self.mxid}", e)
mautrix.errors.base.IntentError: **('Failed to register @googlechatbot:snf.fr', MExclusive('Invalid user localpart for this application service.'))**
````

What's the problem ? it's necessary to create a user googlechatbot on my matrix server ?

**Comment by barto95100** [comment]
The problem is solved for me

probleme on configuration file and matrix

**Comment by barto95100** [comment]
thank's
