### ISSUE TITLE
Failed to initialize database

### ISSUE THREAD

**Issue by andreclemente** [mautrix/googlechat#80]
Hey, I'm trying to setup the googlechat bridge with docker.
I'm having this error and I have no idea why. Thank you!

`[2022-11-16 17:40:19,164] [CRITICAL@mau.init] Failed to initialize database
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/bridge/bridge.py", line 213, in start_db
    await self.db.start()
  File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/asyncpg.py", line 72, in start
    await super().start()
  File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/database.py", line 101, in start
    await self._check_foreign_tables()
  File "/usr/lib/python3.10/site-packages/mautrix/util/async_db/database.py", line 109, in _check_foreign_tables
    raise ForeignTablesFound("found state_groups_state likely belonging to Synapse")
mautrix.util.async_db.errors.ForeignTablesFound: The database contains foreign tables (found state_groups_state likely belonging to Synapse)
[2022-11-16 17:40:19,167] [INFO@mau.init] You can use --ignore-foreign-tables to ignore this error`

**Comment by tulir** [comment]
Sharing databases between different programs is not allowed
